#TEST ENDPOINT WITH GOLAND

### Get All Categories
GET http://localhost:3000/api/categories
X-API-Key: RAHASIA
Accept: application/json


### Create New Category
POST http://localhost:3000/api/categories
X-API-Key: RAHASIA
Accept: application/json
Content-Type: application/json

{
  "name": "Computer"
}

### Get Category By Id
GET http://localhost:3000/api/categories/2
X-API-Key: RAHASIA
Accept: application/json

### Update Category By Id
PUT http://localhost:3000/api/categories/1
X-API-Key: RAHASIA
Accept: application/json
Content-Type: application/json

{
  "name": "Fashion"
}


### Delete Category By Id
DELETE http://localhost:3000/api/categories/3
X-API-Key: RAHASIA
Accept: application/json